import json

BEFORE_FILE = r'C:\Users\AKSHITH REDDY\.gemini\antigravity-ide\brain\955b33d6-bd38-4a59-b378-5057d7f96fc8\scratch\benchmark_phase2_before.json'
AFTER_FILE = r'C:\Users\AKSHITH REDDY\.gemini\antigravity-ide\brain\955b33d6-bd38-4a59-b378-5057d7f96fc8\scratch\benchmark_phase2_after.json'
REPORT_FILE = r'C:\Users\AKSHITH REDDY\.gemini\antigravity-ide\brain\955b33d6-bd38-4a59-b378-5057d7f96fc8\accuracy_report_v2.md'

with open(BEFORE_FILE, 'r') as f:
    before_data = json.load(f)

with open(AFTER_FILE, 'r') as f:
    after_data = json.load(f)

before_dict = {i['name']: i for i in before_data}
after_dict = {i['name']: i for i in after_data}

report = []
report.append("# Accuracy Phase 2 - Scientific Benchmark Report\n")

report.append("## Nutrient Context Engine Evaluation\n")
report.append("The legacy engine evaluated nutrients in a vacuum. The Phase 2 engine evaluates Satiety, Nutrient Density, Protein Quality, and Sugar Quality.\n\n")

report.append("| Product | Satiety Score | Protein Quality | Sugar Quality | Nutrient Density |\n")
report.append("|---------|---------------|-----------------|---------------|------------------|\n")

for name in list(before_dict.keys())[:10]:
    a = after_dict[name]
    report.append(f"| {name} | {a.get('satiety_score', 0)} | {a.get('protein_quality_score', 0)} | {a.get('sugar_quality_score', 0)} | {a.get('nutrient_density_score', 0)} |\n")

report.append("\n## Goal Alignment Engine V2 (Goal: Weight Loss)\n")
report.append("Detailed reasoning logic generated by the engine instead of static phrases.\n\n")

for name in ["Soda", "Greek Yogurt", "Protein Bar", "Monster Energy"]:
    b = before_dict[name]
    a = after_dict[name]
    report.append(f"### {name}\n")
    report.append(f"- **Before Score**: {b.get('goal_alignment_score', 0)}\n")
    report.append(f"- **After Score**: {a.get('goal_alignment_score', 0)}\n")
    report.append(f"- **Phase 2 Reasoning**: {' '.join(a.get('goal_specific_reasoning', []))}\n\n")

report.append("## Explanation Engine Evaluation\n")
report.append("Every deduction now carries a structured explanation.\n\n")

a = after_dict["Snickers"]
report.append(f"### Snickers Score Deductions\n")
for d in a.get('score_deductions', []):
    report.append(f"- **{d['points_deducted']} points**: {d['reason']} (*{d['health_impact']}*)\n")
    
report.append("\n")
a = after_dict["Doritos"]
report.append(f"### Doritos Score Deductions\n")
for d in a.get('score_deductions', []):
    report.append(f"- **{d['points_deducted']} points**: {d['reason']} (*{d['health_impact']}*)\n")

with open(REPORT_FILE, 'w') as f:
    f.writelines(report)

print("Report generated.")
