"""Sync user roles and profiles

Revision ID: 4808df7e45a6
Revises: ce9ddaee73f7
Create Date: 2026-06-04 23:49:46.871016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4808df7e45a6'
down_revision: Union[str, Sequence[str], None] = 'ce9ddaee73f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('health_summary', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('positives', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('ingredient_explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('consumption_guidance', sa.String(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.alter_column('ai_recommendations', 'alternatives',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='alternatives::jsonb')
    op.drop_column('ai_recommendations', 'recommendation')
    op.add_column('food_scores', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('food_scores', sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('food_scores', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('food_scores', 'warnings')
    op.drop_column('food_scores', 'flags')
    op.drop_column('food_scores', 'classification')
    op.add_column('ai_recommendations', sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ai_recommendations', 'alternatives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('ai_recommendations', 'ai_summary')
    op.drop_column('ai_recommendations', 'consumption_guidance')
    op.drop_column('ai_recommendations', 'ingredient_explanations')
    op.drop_column('ai_recommendations', 'concerns')
    op.drop_column('ai_recommendations', 'positives')
    op.drop_column('ai_recommendations', 'health_summary')
    # ### end Alembic commands ###
