"""Add intelligence engine columns

Revision ID: 5410dc5c388b
Revises: 92fe065d9cbc
Create Date: 2026-06-05 22:28:44.671238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5410dc5c388b'
down_revision: Union[str, Sequence[str], None] = '92fe065d9cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_scores', sa.Column('nutrition_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('food_scores', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('food_scores', sa.Column('personalized_analysis', sa.String(), nullable=True))
    op.add_column('food_scores', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_scores', 'recommendations')
    op.drop_column('food_scores', 'personalized_analysis')
    op.drop_column('food_scores', 'score_breakdown')
    op.drop_column('food_scores', 'nutrition_breakdown')
    # ### end Alembic commands ###
