"""Add disease compatibility

Revision ID: 5f6eb8054679
Revises: 772ba3bef75f
Create Date: 2026-06-22 17:46:18.950504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6eb8054679'
down_revision: Union[str, Sequence[str], None] = '772ba3bef75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('disease_compatibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_recommendations', 'disease_compatibility')
    # ### end Alembic commands ###
