"""Add advanced BMI and AI columns

Revision ID: 772ba3bef75f
Revises: 88c10567e324
Create Date: 2026-06-22 16:54:53.005925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772ba3bef75f'
down_revision: Union[str, Sequence[str], None] = '88c10567e324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmi_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('health_assessment', sa.String(), nullable=True),
    sa.Column('ideal_weight_range', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Integer(), nullable=False),
    sa.Column('carb_target_g', sa.Integer(), nullable=False),
    sa.Column('fat_target_g', sa.Integer(), nullable=False),
    sa.Column('water_target_liters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_recommendations', sa.Column('goal_compatibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('processing_level', sa.String(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('processing_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_recommendations', 'processing_reason')
    op.drop_column('ai_recommendations', 'processing_level')
    op.drop_column('ai_recommendations', 'score_breakdown')
    op.drop_column('ai_recommendations', 'goal_compatibility')
    op.drop_table('user_goals')
    op.drop_table('nutrition_targets')
    op.drop_table('bmi_history')
    # ### end Alembic commands ###
