"""Add OCR and Analysis JSON to ScanHistory

Revision ID: 7eeace1f8d71
Revises: 4808df7e45a6
Create Date: 2026-06-05 16:51:10.777395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eeace1f8d71'
down_revision: Union[str, Sequence[str], None] = '4808df7e45a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_history', sa.Column('raw_ocr_text', sa.String(), nullable=True))
    op.add_column('scan_history', sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_history', sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_history', sa.Column('ocr_time_ms', sa.Float(), nullable=True))
    op.add_column('scan_history', sa.Column('extraction_time_ms', sa.Float(), nullable=True))
    op.add_column('scan_history', sa.Column('analysis_time_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_history', 'analysis_time_ms')
    op.drop_column('scan_history', 'extraction_time_ms')
    op.drop_column('scan_history', 'ocr_time_ms')
    op.drop_column('scan_history', 'analysis_json')
    op.drop_column('scan_history', 'extracted_json')
    op.drop_column('scan_history', 'raw_ocr_text')
    # ### end Alembic commands ###
