"""Add dynamic JSON columns

Revision ID: 820d96f31186
Revises: 5410dc5c388b
Create Date: 2026-06-06 00:09:48.026292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820d96f31186'
down_revision: Union[str, Sequence[str], None] = '5410dc5c388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_facts', sa.Column('dynamic_facts', sa.JSON(), nullable=True))
    op.add_column('nutrition_facts', sa.Column('vitamins', sa.JSON(), nullable=True))
    op.add_column('nutrition_facts', sa.Column('minerals', sa.JSON(), nullable=True))
    op.add_column('nutrition_facts', sa.Column('amino_acids', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('allergens', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('additives', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('claims', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'claims')
    op.drop_column('products', 'additives')
    op.drop_column('products', 'allergens')
    op.drop_column('nutrition_facts', 'amino_acids')
    op.drop_column('nutrition_facts', 'minerals')
    op.drop_column('nutrition_facts', 'vitamins')
    op.drop_column('nutrition_facts', 'dynamic_facts')
    # ### end Alembic commands ###
