"""add peanuts and wheat to allergies

Revision ID: 870a3083add9
Revises: 5f6eb8054679
Create Date: 2026-06-27 13:03:11.477778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870a3083add9'
down_revision: Union[str, Sequence[str], None] = '5f6eb8054679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('peanuts', sa.Boolean(), nullable=True))
    op.add_column('allergies', sa.Column('wheat', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allergies', 'wheat')
    op.drop_column('allergies', 'peanuts')
    # ### end Alembic commands ###
