"""Expert Nutrition Analyst schema update

Revision ID: 88c10567e324
Revises: 820d96f31186
Create Date: 2026-06-22 16:22:06.224993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c10567e324'
down_revision: Union[str, Sequence[str], None] = '820d96f31186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('health_score', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('weight_loss', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('muscle_gain', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('diabetes', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('hypertension', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('heart_health', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_recommendations', sa.Column('healthier_alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('ai_recommendations', 'alternatives')
    op.drop_column('ai_recommendations', 'ingredient_explanations')
    op.drop_column('ai_recommendations', 'positives')
    op.drop_column('ai_recommendations', 'health_summary')
    op.drop_column('ai_recommendations', 'consumption_guidance')
    op.drop_column('ai_recommendations', 'ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('consumption_guidance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('health_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('positives', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('ingredient_explanations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ai_recommendations', 'healthier_alternatives')
    op.drop_column('ai_recommendations', 'recommendations')
    op.drop_column('ai_recommendations', 'heart_health')
    op.drop_column('ai_recommendations', 'hypertension')
    op.drop_column('ai_recommendations', 'diabetes')
    op.drop_column('ai_recommendations', 'muscle_gain')
    op.drop_column('ai_recommendations', 'weight_loss')
    op.drop_column('ai_recommendations', 'strengths')
    op.drop_column('ai_recommendations', 'summary')
    op.drop_column('ai_recommendations', 'health_score')
    # ### end Alembic commands ###
