"""remove_unused_scan_history_columns

Revision ID: 92fe065d9cbc
Revises: b1ef0746b6e2
Create Date: 2026-06-05 18:03:22.613974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fe065d9cbc'
down_revision: Union[str, Sequence[str], None] = 'b1ef0746b6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_history', 'safety_level')
    op.drop_column('scan_history', 'ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_history', sa.Column('ai_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan_history', sa.Column('safety_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
